spring.application.name=simulator
# PostgreSQL Connection Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/simulator
spring.datasource.username=asmaa123
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8083
openai.api.key =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
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect