# Application properties
spring.application.name=simulator
server.port=8083

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.ma.hariti.asmaa.wrm.simulator=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/simulator
spring.datasource.username=asmaa

spring.datasource.driver-class-name=org.postgresql.Driver
# Mail (using env variables)
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${MAIL_USERNAME}

# OpenAI API Key
openai.api.key=${OPENAI_API_KEY}

# JWT Configuration
spring.security.jwt.secret-key=${JWT_SECRET}
spring.security.jwt.expiration=86400000
spring.security.jwt.refresh-token.expiration=604800000
spring.security.jwt.remember-me.expiration=2592000000
